apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      jobTemplate: 
        spec:
          containers:
          - name: 'test-cronjob'
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo TESSS CLUSTER
          restartPolicy: OnFailure